# frozen_string_literal: true

module Sightseeing
  Vista = Struct.new(:id, :name, :zone, :coordinates, :weather, :hours, :emote, :comment) do
    class << self
      def build(hash)
        new(*hash.values_at(*members))
      end

      def all
        @_all ||= VistaData.map do |hash|
          build(hash)
        end
      end

      def find(*ids)
        Vista.all.select { |vista| ids.include?(vista[:id]) }
      end
    end

    def matching_hours(forecast)
      return [] unless zone == forecast.zone.id
      return [] unless weather.include?(forecast.weather)
      forecast_hours = forecast.start_hour .. (forecast.end_hour-1) % 24
      hours.intersection(forecast_hours.to_a)
    end
  end

  VistaData = [
    {
      id: 1,
      name: "Barracuda Piers",
      zone: :limsa_lominsa,
      coordinates: "9.5,7.8",
      weather: [:fair_skies,:clear_skies],
      hours: [8,9,10,11],
      emote: "Lookout",
      comment: "Located northwest out of The Bismarck, there are two sets of bricks set into the wall there. The set of bricks closer to the stairs is the Vista location.",
    },
    {
      id: 2,
      name: "The Astalicia",
      zone: :limsa_lominsa,
      coordinates: "7,15",
      weather: [:fair_skies,:clear_skies],
      hours: [18,19,20,21,22,23,0,1,2,3,4],
      emote: "Lookout",
      comment: "Climb to the top of The Astalicia (the ship there), and go east towards the bow of the ship. Climb the pole extending from the ship and go to the very tip.",
    },
    {
      id: 3,
      name: "Seasong Grotto",
      zone: :middle_la_noscea,
      coordinates: "20.3,19.1",
      weather: [:rain],
      hours: [5,6,7],
      emote: "Pray",
      comment: "In the Seasong Grotto, by the entrance.",
    },
    {
      id: 4,
      name: "The Skylift",
      zone: :middle_la_noscea,
      coordinates: "16.0,17.3",
      weather: [:fair_skies,:clear_skies],
      hours: [12,13,14,15,16,17],
      emote: "Lookout",
      comment: "By the Skylift, next to the man overlooking the pier.",
    },
    {
      id: 5,
      name: "La Thagran Eastroad",
      zone: :middle_la_noscea,
      coordinates: "25.3,27.5",
      weather: [:clouds],
      hours: [8,9,10,11],
      emote: "Lookout",
      comment: "Go up the stairs on the east side, and jump up onto the fence post at the top of the stairs.",
    },
    {
      id: 6,
      name: "The Salt Strand",
      zone: :lower_la_noscea,
      coordinates: "23,40",
      weather: [:fair_skies,:clear_skies],
      hours: [18,19,20,21,22,23,0,1,2,3,4],
      emote: "Lookout",
      comment: "Jump onto the base of the rock near the cliff west of the farmer's house.",
    },
    {
      id: 7,
      name: "Red Rooster Stead",
      zone: :lower_la_noscea,
      coordinates: "33,19",
      weather: [:fog],
      hours: [5,6,7],
      emote: "Lookout",
      comment: "Jump on the top of the gate structure for the portal that leads to Mist.",
    },
    {
      id: 8,
      name: "Brewer's Beacon",
      zone: :western_la_noscea,
      coordinates: "29.9,30.7",
      weather: [:fair_skies,:clear_skies],
      hours: [5,6,7],
      emote: "Lookout",
      comment: "Go behind the lighthouse on the west side. The vista is located where the wooden barrier and the lighthouse's wall meet.",
    },
    {
      id: 9,
      name: "The Leatherworkers' Guild",
      zone: :gridania,
      coordinates: "12.8,7.8",
      weather: [:clouds],
      hours: [12,13,14,15,16,17],
      emote: "Lookout",
      comment: "From inside the guild you go up the steps in the back, jump on the table against the right wall, jump again to get onto the higher shelf. Face the room and use Lookout.",
    },
    {
      id: 10,
      name: "Apkallu Falls",
      zone: :gridania,
      coordinates: "10,6",
      weather: [:fair_skies,:clear_skies],
      hours: [18,19,20,21,22,23,0,1,2,3,4],
      emote: "Lookout",
      comment: "Near Apkallu Falls, there are 3 lamp posts. You have to climb onto the cliff on the southeast (10.4, 6.6) and from there use sprint and jump onto the top of the lamp post closest to the waterfall. The lamp post lights must be on for it to complete (after sunset).",
    },
    {
      id: 11,
      name: "Bentbranch Meadows",
      zone: :central_shroud,
      coordinates: "21.8,21.8",
      weather: [:fair_skies,:clear_skies],
      hours: [12,13,14,15,16,17],
      emote: "Sit",
      comment: "The Vista is right next to the Aetheryte. There are three stumps across the Moogle mail carrier. A woman is sitting on the first one. Hop up onto the third one to reach the Vista.",
    },
    {
      id: 12,
      name: "The Sanctum of the Twelve",
      zone: :east_shroud,
      coordinates: "17.6,18.2",
      weather: [:fair_skies,:clear_skies],
      hours: [8,9,10,11],
      emote: "Pray",
      comment: "At the entrance to the chamber to the garden around the Sanctum of the Twelve.",
    },
    {
      id: 13,
      name: "Little Solace",
      zone: :east_shroud,
      coordinates: "22.3,26.2",
      weather: [:fair_skies,:clear_skies],
      hours: [18,19,20,21,22,23,0,1,2,3,4],
      emote: "Lookout",
      comment: "Just behind the Sylph Vendor NPC, on the top of the tree branch extending from the quest NPC platform.",
    },
    {
      id: 14,
      name: "Royal Promenade",
      zone: :uldah,
      coordinates: "11.1,11.6",
      weather: [:fair_skies,:clear_skies],
      hours: [5,6,7],
      emote: "Salute",
      comment: "There are three silver squares in front of the Royal Promenade (players can get there from the Chamber of Rule Aetheryte Shard). The Vista is on the tip of the triangle. Face the stairs and guards then use Salute.",
    },
    {
      id: 15,
      name: "The Gold Court",
      zone: :uldah,
      coordinates: "11.5,11.2",
      weather: [:clouds],
      hours: [12,13,14,15,16,17],
      emote: "Lookout",
      comment: "Jump from Hustings Strip balcony down onto the eastern-most lamp.",
    },
    {
      id: 16,
      name: "The Jewel of the Desert",
      zone: :western_thanalan,
      coordinates: "22.3,22.3",
      weather: [:fair_skies,:clear_skies],
      hours: [18,19,20,21,22,23,0,1,2,3,4],
      emote: "Lookout",
      comment: "Use your mount and jump from the boulder to the awning (the cloth roof) at the beginning of the staircase.",
    },
    {
      id: 17,
      name: "The Ruins of Sil'dih",
      zone: :central_thanalan,
      coordinates: "15.9,22.9",
      weather: [:fog],
      hours: [8,9,10,11],
      emote: "Lookout",
      comment: "About half way down the cliff, where the cliff meets the creek.",
    },
    {
      id: 18,
      name: "The Lonely Giant",
      zone: :eastern_thanalan,
      coordinates: "19.5,24.7",
      weather: [:rain,:showers],
      hours: [17],
      emote: "Comfort",
      comment: "It is located under the base of the tree clump across from the Goobbue.",
    },
    {
      id: 19,
      name: "The Invisible City",
      zone: :eastern_thanalan,
      coordinates: "14.3,18.5",
      weather: [:clouds],
      hours: [8,9,10,11],
      emote: "Lookout",
      comment: "At the tip of the ruin/roof that overlooks the area.",
    },
    {
      id: 20,
      name: "Highbridge",
      zone: :eastern_thanalan,
      coordinates: "21.0,20.7",
      weather: [:fair_skies,:clear_skies],
      hours: [5,6,7],
      emote: "Pray",
      comment: "The Vista is on the small platform that sticks out from underneath the north side of the bridge. It is closest to the NPC located in the carved area on the side of the canyon.",
    },
    {
      id: 21,
      name: "Woad Whisper Canyon",
      zone: :middle_la_noscea,
      coordinates: "20.0,13.1",
      weather: [:fair_skies,:clear_skies],
      hours: [12,13,14,15,16,17],
      emote: "Lookout",
      comment: "Edge of the path, before you pass under the rocky archways.",
    },
    {
      id: 22,
      name: "Summerford Farms",
      zone: :middle_la_noscea,
      coordinates: "25.7,17",
      weather: [:fair_skies,:clear_skies],
      hours: [5,6,7],
      emote: "Lookout",
      comment: "Second floor of Inn. Top of lamp to left of door. Jump on pot plant, then to partition, then to top of lamp.",
    },
    {
      id: 23,
      name: "The Grey Fleet",
      zone: :lower_la_noscea,
      coordinates: "31.5,12.7",
      weather: [:rain],
      hours: [12,13,14,15,16,17],
      emote: "Lookout",
      comment: "On top of the house of sticks. Use the rocks behind the house to get onto the roof.",
    },
    {
      id: 24,
      name: "Hidden Falls",
      zone: :eastern_la_noscea,
      coordinates: "32.6,23.5",
      weather: [:fair_skies,:clear_skies],
      hours: [8,9,10,11],
      emote: "Sit",
      comment: "Sit on chair at end of dock.",
    },
    {
      id: 25,
      name: "Gullperch Tower",
      zone: :eastern_la_noscea,
      coordinates: "29.6,33.8",
      weather: [:rain],
      hours: [18,19,20,21,22,23,0,1,2,3,4],
      emote: "Lookout",
      comment: "On top of Gullperch Tower. Located on the edge of the wall to the left of the two lookout NPCs.",
    },
    {
      id: 26,
      name: "The Navigator",
      zone: :western_la_noscea,
      coordinates: "26.9,26.6",
      weather: [:fair_skies,:clear_skies],
      hours: [17],
      emote: "Pray",
      comment: "To the left hand side along the railing (if lookout out towards the sea).",
    },
    {
      id: 27,
      name: "The Ship Graveyard",
      zone: :western_la_noscea,
      coordinates: "17.1,36.2",
      weather: [:gales],
      hours: [18,19,20,21,22,23,0,1,2,3,4],
      emote: "Lookout",
      comment: "Bottom SE corner of Isle of Umbral. Stand on top of the pot in the sand.",
    },
    {
      id: 28,
      name: "Camp Skull Valley",
      zone: :western_la_noscea,
      coordinates: "22.8,22.4",
      weather: [:fair_skies,:clear_skies],
      hours: [8,9,10,11],
      emote: "Lookout",
      comment: "On top of the front-right spike (if facing) of the tents on the top of the fort. Jump on canvas roof then on spike.",
    },
    {
      id: 29,
      name: "Tidegate",
      zone: :western_la_noscea,
      coordinates: "19.4,23.0",
      weather: [:fair_skies,:clear_skies],
      hours: [12,13,14,15,16,17],
      emote: "Lookout",
      comment: "On the top of the center pole on the round tent (just after three tents). Jump onto the smaller pole then BACKWARDS HOP onto the higher bit. From there sprint jump to the top/middle pole.",
    },
    {
      id: 30,
      name: "Camp Bronze Lake",
      zone: :upper_la_noscea,
      coordinates: "30.8,22.4",
      weather: [:fair_skies,:clear_skies],
      hours: [17],
      emote: "Lookout",
      comment: "Go to the side of the house and jump up on the barrels between the two awnings (jump at the barrels head on, not from the side). Jump up onto the right awning and then onto the rocky ledge. Walk along the edge and jump onto the small part of the roof that juts out. The vista is on the highest point at the front of the house.",
    },
    {
      id: 31,
      name: "Thalaos",
      zone: :upper_la_noscea,
      coordinates: "12.9,22.0",
      weather: [:fair_skies,:clear_skies],
      hours: [12,13,14,15,16,17],
      emote: "Lookout",
      comment: "Very tip of biggest bone/spire. Base of spire starts in (x13,y21). Vista log message did not appear until correct time.",
    },
    {
      id: 32,
      name: "Jijiroon's Trading Post",
      zone: :upper_la_noscea,
      coordinates: "29.1,25.4",
      weather: [:thunderstorms],
      hours: [18,19,20,21,22,23,0,1,2,3,4],
      emote: "Lookout",
      comment: "The vista is on the east side of the arch-like structure. Climb a wall and jump over to the next ruin.",
    },
    {
      id: 33,
      name: "The Floating City of Nym",
      zone: :outer_la_noscea,
      coordinates: "12,15",
      weather: [:fair_skies,:clear_skies],
      hours: [18,19,20,21,22,23,0,1,2,3,4],
      emote: "Lookout",
      comment: "Cliff overlooking Nym.",
    },
    {
      id: 34,
      name: "Camp Overlook",
      zone: :outer_la_noscea,
      coordinates: "17.1,16.3",
      weather: [:clouds],
      hours: [5,6,7],
      emote: "Lookout",
      comment: "Crumbling arch. Climb from the North side. Jump over gap and hop up on highest part. Kind of hidden by bushes.",
    },
    {
      id: 35,
      name: "U'Ghamaro Mines",
      zone: :outer_la_noscea,
      coordinates: "23,11",
      weather: [:fair_skies,:clear_skies],
      hours: [12,13,14,15,16,17],
      emote: "Lookout",
      comment: "On top of the high furnace. Jump from the smaller one to the bigger one. There's a smokestack sticking out of the small one that kind of looks like the exhaust stack on a semi-truck/tractor trailer. If you try to run forward towards the big one, it blocks you. So jump on top of it, and then jump across to the big one.",
    },
    {
      id: 36,
      name: "The Hermit's Hovel",
      zone: :outer_la_noscea,
      coordinates: "15,9",
      weather: [:rain],
      hours: [18,19,20,21,22,23,0,1,2,3,4],
      emote: "Sit",
      comment: "Inside the house jump on the table -> bookshelf -> area with bed and table. stand on the stool and then Sit.",
    },
    {
      id: 37,
      name: "The Carline Canopy",
      zone: :gridania,
      coordinates: "14,14",
      weather: [:fair_skies,:clear_skies],
      hours: [8,9,10,11],
      emote: "Lookout",
      comment: "Blue Badger Gate on the left gate (facing the exit). Jump on railing from stairs. From there sprint jump to door. Then jump from door to door.",
    },
    {
      id: 38,
      name: "The Lancer's Guild",
      zone: :gridania,
      coordinates: "14.2,5.9",
      weather: [:rain],
      hours: [5,6,7],
      emote: "Lookout",
      comment: "Jump on bookshelf then onto weapons to make your way to the corner.",
    },
    {
      id: 39,
      name: "The Bannock",
      zone: :central_shroud,
      coordinates: "23.4,19.9",
      weather: [:rain],
      hours: [5,6,7],
      emote: "Lookout",
      comment: "Jump onto the canvas above the commander's heads by first jumping up and along the tree. The vista is on top of the wooden arch.",
    },
    {
      id: 40,
      name: "Haukke Manor",
      zone: :central_shroud,
      coordinates: "13.6,23.1",
      weather: [:fair_skies,:clear_skies],
      hours: [18,19,20,21,22,23,0,1,2,3,4],
      emote: "Lookout",
      comment: "Climb onto the roots from left side just walk up. Hop onto top. Root are coming off of cliff into a small pond with a view of the mansion.",
    },
    {
      id: 41,
      name: "The Guardian Tree",
      zone: :central_shroud,
      coordinates: "16.3,22.3",
      weather: [:fair_skies,:clear_skies],
      hours: [12,13,14,15,16,17],
      emote: "Lookout",
      comment: "On tree bridge.",
    },
    {
      id: 42,
      name: "Rainbow Bridge",
      zone: :central_shroud,
      coordinates: "26.5,18.8",
      weather: [:fair_skies,:clear_skies],
      hours: [11,12],
      emote: "Lookout",
      comment: "On top and center of waterfall side of railing on bridge.",
    },
    {
      id: 43,
      name: "The Seedbed",
      zone: :east_shroud,
      coordinates: "20,10",
      weather: [:thunder],
      hours: [18,19,20,21,22,23,0,1,2,3,4],
      emote: "Lookout",
      comment: "Right in front of giant glowing mushroom.",
    },
    {
      id: 44,
      name: "Buscarron's Druthers",
      zone: :south_shroud,
      coordinates: "17.8,20.1",
      weather: [:thunderstorms],
      hours: [8,9,10,11],
      emote: "Lookout",
      comment: "On balcony over main bar. Get there by jumping from wall on Eastern back corner of the bar, and onto the roof. Follow it back to the front of the building and sprint jump from roof corner to balcony.",
    },
    {
      id: 45,
      name: "South Shroud Landing",
      zone: :south_shroud,
      coordinates: "14.7,33.9",
      weather: [:fair_skies,:clear_skies],
      hours: [8,9,10,11],
      emote: "Lookout",
      comment: "On the windowsill beside the hut.",
    },
    {
      id: 46,
      name: "Urth's Gift",
      zone: :south_shroud,
      coordinates: "33.3,23.9",
      weather: [:fog],
      hours: [12,13,14,15,16,17],
      emote: "Lookout",
      comment: "At the rock wall.",
    },
    {
      id: 47,
      name: "Quarrymill",
      zone: :south_shroud,
      coordinates: "25,21",
      weather: [:fair_skies,:clear_skies],
      hours: [5,6,7],
      emote: "Lookout",
      comment: "On top of chimney on house farthest from Aetheryte (shaped like a mushroom). Jump from balcony.",
    },
    {
      id: 48,
      name: "Ixali Logging Grounds",
      zone: :north_shroud,
      coordinates: "18.4,19.5",
      weather: [:fair_skies,:clear_skies],
      hours: [12,13,14,15,16,17],
      emote: "Lookout",
      comment: "The middle post on the log-pile at the back of the area. Recommend using flying mount.",
    },
    {
      id: 49,
      name: "Fallen Neurolink",
      zone: :north_shroud,
      coordinates: "16,31",
      weather: [:fair_skies,:clear_skies],
      hours: [18,19,20,21,22,23,0,1,2,3,4],
      emote: "Lookout",
      comment: "Near edge of cliff looking at giant arc.",
    },
    {
      id: 50,
      name: "Alder Springs",
      zone: :north_shroud,
      coordinates: "15.4,27.2",
      weather: [:clouds],
      hours: [8,9,10,11],
      emote: "Lookout",
      comment: "Drop down from above. Start at stump of tree that broke off near edge of cliff and fall down directly below to another root/branch extending out. Take left fork twice. Go SLOW!",
    },
    {
      id: 51,
      name: "Castrum Marinum",
      zone: :western_thanalan,
      coordinates: "8.7,5.2",
      weather: [:fair_skies,:clear_skies],
      hours: [17],
      emote: "Lookout",
      comment: "On the lamp.",
    },
    {
      id: 52,
      name: "Vesper Bay",
      zone: :western_thanalan,
      coordinates: "12.4,14.8",
      weather: [:fair_skies,:clear_skies],
      hours: [12,13,14,15,16,17],
      emote: "Point",
      comment: "Top of the building, north west corner.",
    },
    {
      id: 53,
      name: "Black Brush Station",
      zone: :central_thanalan,
      coordinates: "21.4,17.5",
      weather: [:dust_storms],
      hours: [18,19,20,21,22,23,0,1,2,3,4],
      emote: "Lookout",
      comment: "Jump from the top of the building to the lamp post on the left hand side.",
    },
    {
      id: 54,
      name: "Gate of Nald",
      zone: :central_thanalan,
      coordinates: "18.5,26.1",
      weather: [:fair_skies,:clear_skies],
      hours: [12,13,14,15,16,17],
      emote: "Sit",
      comment: "On top of a canvas.",
    },
    {
      id: 55,
      name: "The Burning Wall",
      zone: :eastern_thanalan,
      coordinates: "30.7,26.5",
      weather: [:fair_skies,:clear_skies],
      hours: [12,13,14,15,16,17],
      emote: "Lookout",
      comment: "On top of the small crystal, drop down from the ledge just above at (x30.7,y26.7,z0.0).",
    },
    {
      id: 56,
      name: "The Golden Bazaar",
      zone: :eastern_thanalan,
      coordinates: "10.0,16.7",
      weather: [:fair_skies,:clear_skies],
      hours: [8,9,10,11],
      emote: "Lookout",
      comment: "On top of the entrance to a collapsed mine, jump to fence. Use fence to jump to higher platform. Vista on top of platform above 2 NPC at the front.",
    },
    {
      id: 57,
      name: "Thal's Respite",
      zone: :eastern_thanalan,
      coordinates: "25,14",
      weather: [:showers],
      hours: [18,19,20,21,22,23,0,1,2,3,4],
      emote: "Pray",
      comment: "In front of the statue.",
    },
    {
      id: 58,
      name: "Nald's Reflection",
      zone: :southern_thanalan,
      coordinates: "12,22",
      weather: [:fog],
      hours: [5,6,7],
      emote: "Pray",
      comment: "In front of the statue.",
    },
    {
      id: 59,
      name: "Zahar'ak",
      zone: :southern_thanalan,
      coordinates: "19.3,20.5",
      weather: [:fair_skies,:clear_skies],
      hours: [5,6,7],
      emote: "Lookout",
      comment: "On top of the stone column. Jump with mount.",
    },
    {
      id: 60,
      name: "The Sagolii Desert",
      zone: :southern_thanalan,
      coordinates: "21.3,38.6",
      weather: [:heat_waves],
      hours: [12,13,14,15,16,17],
      emote: "Lookout",
      comment: "On top of large mound next to tower ruin on ground.",
    },
    {
      id: 61,
      name: "The Sunken Temple of Qarn",
      zone: :southern_thanalan,
      coordinates: "23.8,11.8",
      weather: [:fair_skies,:clear_skies],
      hours: [12,13,14,15,16,17],
      emote: "Lookout",
      comment: "Use rocks to jump up on to the sloped building.",
    },
    {
      id: 62,
      name: "Minotaur Malm",
      zone: :southern_thanalan,
      coordinates: "14.6,26.5",
      weather: [:heat_waves],
      hours: [5,6,7],
      emote: "Psych",
      comment: "Stand beside the drill sergeant near the exercising recruits.",
    },
    {
      id: 63,
      name: "East Watchtower",
      zone: :northern_thanalan,
      coordinates: "22.2,25.7",
      weather: [:fair_skies,:clear_skies],
      hours: [5,6,7],
      emote: "Salute",
      comment: "Salute on top of the tower, on the flagpole.",
    },
    {
      id: 64,
      name: "Ceruleum Pipeline",
      zone: :northern_thanalan,
      coordinates: "20,29",
      weather: [:fair_skies,:clear_skies],
      hours: [18,19,20,21,22,23,0,1,2,3,4],
      emote: "Lookout",
      comment: "On top of the gate, north side.",
    },
    {
      id: 65,
      name: "Bluefog",
      zone: :northern_thanalan,
      coordinates: "20.8,22.5",
      weather: [:fair_skies,:clear_skies],
      hours: [12,13,14,15,16,17],
      emote: "Lookout",
      comment: "On the fence.",
    },
    {
      id: 66,
      name: "Raubahn's Push",
      zone: :northern_thanalan,
      coordinates: "20.0,17.7",
      weather: [:clouds],
      hours: [8,9,10,11],
      emote: "Lookout",
      comment: "On one of the southwestern spires.",
    },
    {
      id: 67,
      name: "Abandoned Amajina Mythril Mine",
      zone: :northern_thanalan,
      coordinates: "26.4,22.7",
      weather: [:fog],
      hours: [18,19,20,21,22,23,0,1,2,3,4],
      emote: "Lookout",
      comment: "On a little ledge attached to a broken pillar near stairs. Go up the stairs at (25.7, 22.7). Jump from the railing to the crumbling stone beam, then walk across the metal beams and make another jump to the broken arch on your right. Finally, Sprint-jump across the gap to the other side.",
    },
    {
      id: 68,
      name: "The Nail",
      zone: :coerthas_central_highlands,
      coordinates: "25.4,29.8",
      weather: [:fair_skies,:clear_skies],
      hours: [17],
      emote: "Lookout",
      comment: "Top of the Observatorium on the ladder under the telescope. Jump onto the lamp closest to the ladder and then onto the ladder itself.",
    },
    {
      id: 69,
      name: "The Observatorium",
      zone: :coerthas_central_highlands,
      coordinates: "25,29",
      weather: [:fog],
      hours: [18,19,20,21,22,23,0,1,2,3,4],
      emote: "Lookout",
      comment: "Take a couple of steps down from the first floor and walk/fall off into the center of the tower, landing on the highest chandelier.",
    },
    {
      id: 70,
      name: "The Frozen Fang",
      zone: :coerthas_central_highlands,
      coordinates: "11.7,15.8",
      weather: [:blizzards],
      hours: [8,9,10,11],
      emote: "Lookout",
      comment: "From the base of the stairs at (11.0,15.5) walk along the small ledge that sticks out until you're at the middle of the semi-circle part of the bridge.",
    },
    {
      id: 71,
      name: "The Holy See of Ishgard",
      zone: :coerthas_central_highlands,
      coordinates: "12.8,17.3",
      weather: [:fair_skies,:clear_skies],
      hours: [5,6,7],
      emote: "Lookout",
      comment: "Top of the tower on the over-arch. After climbing the stone spiral staircase, enter the small room and use the wooden stairs to get all the way up.",
    },
    {
      id: 72,
      name: "Boulder Downs",
      zone: :coerthas_central_highlands,
      coordinates: "7,28",
      weather: [:fair_skies,:clear_skies],
      hours: [17],
      emote: "Lookout",
      comment: "Top of monument tower next to the NPC standing next to the top of the stairs.",
    },
    {
      id: 73,
      name: "The Fury's Gaze",
      zone: :coerthas_central_highlands,
      coordinates: "7.9,31.3",
      weather: [:blizzards],
      hours: [18,19,20,21,22,23,0,1,2,3,4],
      emote: "Lookout",
      comment: "Inside the cave before you reach the plasmoids.",
    },
    {
      id: 74,
      name: "Snowcloak",
      zone: :coerthas_central_highlands,
      coordinates: "2.2,21.4",
      weather: [:fair_skies,:clear_skies],
      hours: [8,9,10,11],
      emote: "Lookout",
      comment: "Climb up to the highest ledge.",
    },
    {
      id: 75,
      name: "Camp Dragonhead",
      zone: :coerthas_central_highlands,
      coordinates: "26.5,17.7",
      weather: [:fair_skies,:clear_skies],
      hours: [12,13,14,15,16,17],
      emote: "Lookout",
      comment: "Climb up to the eastern battlements and head south to draw parallel to the green-roofed building. Jump up onto a higher crenelation that's in line with a buttress opposite and sprint one step and jump over to the building.",
    },
    {
      id: 76,
      name: "The Steel Vigil",
      zone: :coerthas_central_highlands,
      coordinates: "28.2,10.3",
      weather: [:fair_skies,:clear_skies],
      hours: [5,6,7],
      emote: "Lookout",
      comment: "On the broken arch of the ruins. Start climbing from the most South Eastern edge of the broken wall. The vista is just on the other side of the steeple.",
    },
    {
      id: 77,
      name: "Castrum Centri",
      zone: :mor_dhona,
      coordinates: "9.8,13.5",
      weather: [:gloom],
      hours: [12,13,14,15,16,17],
      emote: "Lookout",
      comment: "On top of red light just past four cylinders. Jump up onto the smaller ledge and then onto the ledge leading towards the light.",
    },
    {
      id: 78,
      name: "The Crystal Tower",
      zone: :mor_dhona,
      coordinates: "27.4,8.0",
      weather: [:fair_skies,:clear_skies],
      hours: [18,19,20,21,22,23,0,1,2,3,4],
      emote: "Lookout",
      comment: "Follow path that curves to the left to go to the upper level. Vista is near a tree by the edge.",
    },
    {
      id: 79,
      name: "Rathefrost",
      zone: :mor_dhona,
      coordinates: "18.6,17.7",
      weather: [:fair_skies,:clear_skies],
      hours: [12,13,14,15,16,17],
      emote: "Lookout",
      comment: "On top of rock near crystal tree.",
    },
    {
      id: 80,
      name: "The Keeper of the Lake",
      zone: :mor_dhona,
      coordinates: "26.1,11.2",
      weather: [:fair_skies,:clear_skies],
      hours: [17],
      emote: "Sit",
      comment: "Sit on top of tree. Climb the back of the red metallic wreckage near a smaller red cylinder. Walk up and jump on small metal rib. From there jump onto back of Big broken red metallic hull. It's also possible, with maximum mount speed, to jump from the branch of the next-closest tree.",
    }
  ]
end
